#include <Modex.h>

// TODO: For efficientcy forward declare the script classes.
#include "../Assets/Scripts/TestScript.h"

// Auto generated by Codex Reflector.
// This file contains metadata about classes and fields that were marked for serialization.

using namespace codex;

std::unordered_map<const char*, NativeBehaviour* (*)()> g_Classes;

extern "C" CODEX_EXPORT bool             Rf_DoesInstanceExist(const char* className);
extern "C" CODEX_EXPORT NativeBehaviour* Rf_CreateInstance(const char* className);
extern "C" CODEX_EXPORT void             Rf_Dummy()
{
}

bool Rf_DoesInstanceExist(const char* className)
{
    if (std::strcmp(className, "MienScripten") == 0)
        return true;
    return false;
}

NativeBehaviour* Rf_CreateInstance(const char* className)
{
    std::printf("Creating instance of: %s\n", className);
    if (std::strcmp(className, "MienScripten") == 0)
        return new MienScripten();
    else
        return nullptr;
}
