#include <Modex.h>
#include <Reflector.h>

// To be added by Reflector.
#include "../Assets/Scripts/TestScript.h"

// Auto generated by Codex Reflector.
// This file contains metadata about classes and fields that were marked for serialization.

using namespace codex;

std::unordered_map<const char*, NativeBehaviour* (*)()> g_Classes;

void Rf_Dummy()
{
    std::puts("Dummy function executed.");
}

bool Rf_DoesInstanceExist(const char* className)
{
    if (std::strcmp(className, "MienScripten") == 0)
        return true;
    return false;
}

NativeBehaviour* Rf_CreateInstance(const char* className)
{
    // There was an issue with entity owner I don't know, I don't remember.
    std::printf("Creating instance of: %s\n", className);
    if (std::strcmp(className, "MienScripten") == 0)
        return new MienScripten();
    return nullptr;
}
