// Auto-generated by Codex Reflector.

#include "..\Assets\Scripts\TestScript.h"

#include <cstdio>
#include <Codex.h>

void Rf_Dummy() noexcept { std::puts("dummy was called."); }

bool Rf_DoesInstanceExist(const char* className) noexcept
{
 if (std::strcmp(className, "MienScripten") == 0)
  return true;
 return false;
}

codex::NativeBehaviour* Rf_CreateInstance(const char* className) noexcept
{
 if (std::strcmp(className, "MienScripten") == 0)
  return new MienScripten;
 return nullptr;
}

