#include <Modex.h>

// To be added by Reflector.
#include "../Assets/Scripts/TestScript.h"

// Auto generated by Codex Reflector.
// This file contains metadata about classes and fields that were marked for serialization.

using namespace codex;

void Rf_Dummy() noexcept
{
    std::puts("Dummy function executed.");
}

bool Rf_DoesInstanceExist(const char* className) noexcept
{
    return false;
}

NativeBehaviour* Rf_CreateInstance(const char* className) noexcept
{
    // There was an issue with entity owner I don't know, I don't remember.
    std::printf("Creating instance of: %s\n", className);
    return nullptr;
}
