// Auto-generated by Codex Reflector.

#include "../Assets/Scripts/TestScript.h"

/*
void MienScripten::Serialize()
{
    m_SerializedData["MienScripten"]["Id"]                              = 0;
    m_SerializedData["MienScripten"]["Fields"]["m_Multiplier"]["Type"]  = FieldType::F32;
    m_SerializedData["MienScripten"]["Fields"]["m_Multiplier"]["Value"] = m_Multiplier;
    m_SerializedData["MienScripten"]["Fields"]["m_Move"]["Type"]        = FieldType::Boolean;
    m_SerializedData["MienScripten"]["Fields"]["m_Move"]["Value"]       = m_Move;
    m_SerializedData["MienScripten"]["Fields"]["m_Axies"]["Type"]       = FieldType::Vector3f;
    m_SerializedData["MienScripten"]["Fields"]["m_Axies"]["Value"]      = m_Axies;
}

object MienScripten::GetField(const std::string_view name)
{
    if (std::strncmp(name.data(), "m_Multiplier", name.size()) == 0)
        return &m_Multiplier;
    else if (std::strncmp(name.data(), "m_Move", name.size()) == 0)
        return &m_Move;
    else if (std::strncmp(name.data(), "m_Axies", name.size()) == 0)
        return &m_Axies;
    return nullobj;
}
*/
